DROP TABLE IF EXISTS user_stocks CASCADE;

CREATE TABLE user_stocks (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, 
  stock_id INTEGER REFERENCES stocks(id) ON DELETE CASCADE
)